apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - configMapRef:
                name: genlayer-sim-env-config
          volumeMounts:
            - name: examples
              mountPath: /app/src/assets/examples
      volumes:
        - name: examples
          hostPath:
            path: /path/to/examples
