name: Release Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main  # or your default branch name

jobs:
  trigger-infra-workflow:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infra Deploy Studio to Staging Environment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.CI_BOT_SECRET }}" \
            https://api.github.com/repos/yeagerai/genlayer-simulator-infra/actions/workflows/deploy-stage.yml/dispatches \
            -d '{"ref":"main"}' 